# Generated by Django 5.1.1 on 2024-10-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClassEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(
                        choices=[
                            ("Math", "Math"),
                            ("German", "German"),
                            ("Eng", "English"),
                            ("Bio", "Biology"),
                            ("Chem", "Chemistry"),
                            ("PE", "Physical Education"),
                            ("HST", "History"),
                            ("Art", "Art"),
                            ("Geo", "Geography"),
                            ("Phi", "Philosophy"),
                            ("Eth", "Ethics"),
                            ("Rel", "Religion"),
                            ("Spa", "Spanish"),
                            ("Fre", "French"),
                            ("Lat", "Latin"),
                        ],
                        max_length=30,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Mon", "Monday"),
                            ("Tue", "Tuesday"),
                            ("Wed", "Wednesday"),
                            ("Thu", "Thursday"),
                            ("Fri", "Friday"),
                            ("Sat", "Saturday"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("date", models.DateTimeField()),
                ("description", models.TextField()),
            ],
        ),
    ]
