# Generated by Django 5.1.1 on 2024-09-26 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classroom", "0001_initial"),
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classenvironment",
            name="teacher",
            field=models.ManyToManyField(to="userprofile.teacher"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="classenvironment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classroom.classenvironment",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userprofile.teacher"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="class_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classroom.classenvironment",
            ),
        ),
    ]
