# Generated by Django 5.1.1 on 2024-09-25 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classroom", "0002_initial"),
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("late", "late"), ("absent", "absent")], max_length=10
                    ),
                ),
                (
                    "lesson_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classroom.lesson",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userprofile.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "lesson_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classroom.lesson",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Homework_Uncompleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "homework_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homeworkflow.homework",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userprofile.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Weekly_Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateField(auto_now_add=True)),
                ("written_feedback", models.TextField()),
                (
                    "social_behaviour",
                    models.CharField(
                        choices=[
                            ("excellent", "excellent"),
                            ("good", "good"),
                            ("average", "average"),
                            ("poor", "poor"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "work_ethics",
                    models.CharField(
                        choices=[
                            ("excellent", "excellent"),
                            ("good", "good"),
                            ("average", "average"),
                            ("poor", "poor"),
                        ],
                        max_length=10,
                    ),
                ),
                ("parent_checked", models.BooleanField(default=False)),
                (
                    "attendance_rate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="homeworkflow.attendance",
                    ),
                ),
                (
                    "homework_completion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="homeworkflow.homework_uncompleted",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userprofile.student",
                    ),
                ),
                (
                    "teacher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="userprofile.teacher",
                    ),
                ),
            ],
        ),
    ]
