# Generated by Django 5.1.1 on 2024-10-09 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("classroom", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Homework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("due_date", models.DateField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Homework_Uncompleted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Weekly_Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("homework_completion", models.FloatField(blank=True, null=True)),
                ("attendance_rate", models.FloatField(blank=True, null=True)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("written_feedback", models.TextField()),
                (
                    "social_behaviour",
                    models.CharField(
                        choices=[
                            ("excellent", "excellent"),
                            ("good", "good"),
                            ("average", "average"),
                            ("poor", "poor"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "work_ethics",
                    models.CharField(
                        choices=[
                            ("excellent", "excellent"),
                            ("good", "good"),
                            ("average", "average"),
                            ("poor", "poor"),
                        ],
                        max_length=10,
                    ),
                ),
                ("parent_checked", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("late", "late"), ("absent", "absent")], max_length=10
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classroom.lesson",
                    ),
                ),
            ],
        ),
    ]
