# Generated by Django 5.1.1 on 2024-09-26 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classroom", "0002_initial"),
        ("homeworkflow", "0001_initial"),
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="absence",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userprofile.student"
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="lesson_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="classroom.lesson"
            ),
        ),
        migrations.AddField(
            model_name="homework_uncompleted",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="homeworkflow.homework"
            ),
        ),
        migrations.AddField(
            model_name="homework_uncompleted",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userprofile.student"
            ),
        ),
        migrations.AddField(
            model_name="weekly_feedback",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="userprofile.student"
            ),
        ),
        migrations.AddField(
            model_name="weekly_feedback",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="userprofile.teacher"
            ),
        ),
    ]
