# Generated by Django 5.1.1 on 2024-10-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeworkflow", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weekly_feedback",
            name="attendance_rate",
        ),
        migrations.RemoveField(
            model_name="weekly_feedback",
            name="homework_completion",
        ),
        migrations.AddField(
            model_name="weekly_feedback",
            name="days_missing",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="weekly_feedback",
            name="lessons_late",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
